spring.application.name=RTD-Notification-Service
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/RTD-NotificationService
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=metropol
spring.datasource.password=20002002
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=karslitugrulhan@gmail.com
spring.mail.password=qyow dpnl loxl udcc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# RabbitMQ Configuration
spring.rabbitmq.uri=amqps://okzwdbrz:AmGKgw5DTXuIAjOraNCNzFiqI5_lhV-s@kebnekaise.lmq.cloudamqp.com/okzwdbrz
spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.listener.simple.missing-queues-fatal=false
spring.rabbitmq.listener.simple.default-requeue-rejected=false
